### ISSUE TITLE
Can not use tags that include "-" (hyphen) sign  

### ISSUE THREAD

**Issue by eyovel-perfecto** [Quantum-js/quantum-wdio#1]
When using tags with a hyphen sign such as @lloyds-eyal no feature file will be found and the message in the terminal will be: 

tagExpression(@lloyds-eyal)
FEATURE PATH./src/features/**/*.feature
found 0 common features..

**Comment by hadasshani** [comment]
Fixed the issue, will be released version 1.1.14
